Func EnterName()

	; Load characters showing EnterName into the scrape character bank

	Local $bankName = "EnterName" 	
	Local $numberCharacters = 51

	; Don't load the bank if it's already loaded with these characters, or if there are too many characters
	If $Char_set_name = $bankName Then
		Return "success"	
	ElseIf $numberCharacters > $Char_maxChars Then
		Return "fail"	
	Else
		; Otherwise, empty the charbank and then refill it
		Util_EmptyCharBank()
		$Char_set_name = $bankName
		$Char_bank_number = $numberCharacters
	EndIf

	; Character i
	$Char_bank_chr[1]    = "i"
	$Char_bank_width[1]  = "1"
	$Char_bank_height[1] = "8"
	$Char_bank[1][1]     = "x"
	$Char_bank[1][2]     = " "
	$Char_bank[1][3]     = "x"
	$Char_bank[1][4]     = "x"
	$Char_bank[1][5]     = "x"
	$Char_bank[1][6]     = "x"
	$Char_bank[1][7]     = "x"
	$Char_bank[1][8]     = "x"

	; Character n
	$Char_bank_chr[2]    = "n"
	$Char_bank_width[2]  = "5"
	$Char_bank_height[2] = "6"
	$Char_bank[2][1]     = "xxxx "
	$Char_bank[2][2]     = "x   x"
	$Char_bank[2][3]     = "x   x"
	$Char_bank[2][4]     = "x   x"
	$Char_bank[2][5]     = "x   x"
	$Char_bank[2][6]     = "x   x"

	; Character 4
	$Char_bank_chr[3]    = "4"
	$Char_bank_width[3]  = "5"
	$Char_bank_height[3] = "8"
	$Char_bank[3][1]     = "   x "
	$Char_bank[3][2]     = "  xx "
	$Char_bank[3][3]     = " x x "
	$Char_bank[3][4]     = "x  x "
	$Char_bank[3][5]     = "xxxxx"
	$Char_bank[3][6]     = "   x "
	$Char_bank[3][7]     = "   x "
	$Char_bank[3][8]     = "   x "

	; Character 0
	$Char_bank_chr[4]    = "0"
	$Char_bank_width[4]  = "5"
	$Char_bank_height[4] = "8"
	$Char_bank[4][1]     = " xxx "
	$Char_bank[4][2]     = "x   x"
	$Char_bank[4][3]     = "x   x"
	$Char_bank[4][4]     = "x   x"
	$Char_bank[4][5]     = "x   x"
	$Char_bank[4][6]     = "x   x"
	$Char_bank[4][7]     = "x   x"
	$Char_bank[4][8]     = " xxx "

	; Character m
	$Char_bank_chr[5]    = "m"
	$Char_bank_width[5]  = "7"
	$Char_bank_height[5] = "6"
	$Char_bank[5][1]     = "xxx xx "
	$Char_bank[5][2]     = "x  x  x"
	$Char_bank[5][3]     = "x  x  x"
	$Char_bank[5][4]     = "x  x  x"
	$Char_bank[5][5]     = "x  x  x"
	$Char_bank[5][6]     = "x  x  x"

	; Character u
	$Char_bank_chr[6]    = "u"
	$Char_bank_width[6]  = "5"
	$Char_bank_height[6] = "6"
	$Char_bank[6][1]     = "x   x"
	$Char_bank[6][2]     = "x   x"
	$Char_bank[6][3]     = "x   x"
	$Char_bank[6][4]     = "x   x"
	$Char_bank[6][5]     = "x   x"
	$Char_bank[6][6]     = " xxxx"

	; Character t
	$Char_bank_chr[7]    = "t"
	$Char_bank_width[7]  = "3"
	$Char_bank_height[7] = "8"
	$Char_bank[7][1]     = "x  "
	$Char_bank[7][2]     = "x  "
	$Char_bank[7][3]     = "xxx"
	$Char_bank[7][4]     = "x  "
	$Char_bank[7][5]     = "x  "
	$Char_bank[7][6]     = "x  "
	$Char_bank[7][7]     = "x  "
	$Char_bank[7][8]     = " xx"

	; Character e
	$Char_bank_chr[8]    = "e"
	$Char_bank_width[8]  = "5"
	$Char_bank_height[8] = "6"
	$Char_bank[8][1]     = " xxx "
	$Char_bank[8][2]     = "x   x"
	$Char_bank[8][3]     = "xxxxx"
	$Char_bank[8][4]     = "x    "
	$Char_bank[8][5]     = "x   x"
	$Char_bank[8][6]     = " xxx "

	; Character s
	$Char_bank_chr[9]    = "s"
	$Char_bank_width[9]  = "4"
	$Char_bank_height[9] = "6"
	$Char_bank[9][1]     = " xxx"
	$Char_bank[9][2]     = "x   "
	$Char_bank[9][3]     = "xx  "
	$Char_bank[9][4]     = "  xx"
	$Char_bank[9][5]     = "   x"
	$Char_bank[9][6]     = "xxx "

	; Character 6
	$Char_bank_chr[10]    = "6"
	$Char_bank_width[10]  = "6"
	$Char_bank_height[10] = "8"
	$Char_bank[10][1]     = " xxxx "
	$Char_bank[10][2]     = "xx    "
	$Char_bank[10][3]     = "xx    "
	$Char_bank[10][4]     = "xxxxx "
	$Char_bank[10][5]     = "xx  xx"
	$Char_bank[10][6]     = "xx  xx"
	$Char_bank[10][7]     = "xx  xx"
	$Char_bank[10][8]     = " xxxx "

	; Character 8
	$Char_bank_chr[11]    = "8"
	$Char_bank_width[11]  = "6"
	$Char_bank_height[11] = "8"
	$Char_bank[11][1]     = " xxxx "
	$Char_bank[11][2]     = "xx  xx"
	$Char_bank[11][3]     = "xx  xx"
	$Char_bank[11][4]     = " xxxx "
	$Char_bank[11][5]     = "xx  xx"
	$Char_bank[11][6]     = "xx  xx"
	$Char_bank[11][7]     = "xx  xx"
	$Char_bank[11][8]     = " xxxx "

	; Character 5
	$Char_bank_chr[12]    = "5"
	$Char_bank_width[12]  = "6"
	$Char_bank_height[12] = "8"
	$Char_bank[12][1]     = " xxxxx"
	$Char_bank[12][2]     = " xx   "
	$Char_bank[12][3]     = " xx   "
	$Char_bank[12][4]     = " xxxx "
	$Char_bank[12][5]     = "    xx"
	$Char_bank[12][6]     = "    xx"
	$Char_bank[12][7]     = "xx  xx"
	$Char_bank[12][8]     = " xxxx "

	; Character 9
	$Char_bank_chr[13]    = "9"
	$Char_bank_width[13]  = "6"
	$Char_bank_height[13] = "8"
	$Char_bank[13][1]     = " xxxx "
	$Char_bank[13][2]     = "xx  xx"
	$Char_bank[13][3]     = "xx  xx"
	$Char_bank[13][4]     = "xx  xx"
	$Char_bank[13][5]     = " xxxxx"
	$Char_bank[13][6]     = "    xx"
	$Char_bank[13][7]     = "    xx"
	$Char_bank[13][8]     = " xxxx "

	; Character 3
	$Char_bank_chr[14]    = "3"
	$Char_bank_width[14]  = "6"
	$Char_bank_height[14] = "8"
	$Char_bank[14][1]     = " xxxx "
	$Char_bank[14][2]     = "xx  xx"
	$Char_bank[14][3]     = "    xx"
	$Char_bank[14][4]     = "  xxx "
	$Char_bank[14][5]     = "    xx"
	$Char_bank[14][6]     = "    xx"
	$Char_bank[14][7]     = "xx  xx"
	$Char_bank[14][8]     = " xxxx "

	; Character 2
	$Char_bank_chr[15]    = "2"
	$Char_bank_width[15]  = "6"
	$Char_bank_height[15] = "8"
	$Char_bank[15][1]     = " xxxx "
	$Char_bank[15][2]     = "xx  xx"
	$Char_bank[15][3]     = "    xx"
	$Char_bank[15][4]     = "   xx "
	$Char_bank[15][5]     = "  xx  "
	$Char_bank[15][6]     = " xx   "
	$Char_bank[15][7]     = "xx    "
	$Char_bank[15][8]     = "xxxxxx"

	; Character $
	$Char_bank_chr[16]    = "$"
	$Char_bank_width[16]  = "6"
	$Char_bank_height[16] = "11"
	$Char_bank[16][1]     = "   x  "
	$Char_bank[16][2]     = "   x  "
	$Char_bank[16][3]     = " xxxx "
	$Char_bank[16][4]     = "xx x x"
	$Char_bank[16][5]     = "xx x  "
	$Char_bank[16][6]     = " xxxx "
	$Char_bank[16][7]     = "  x xx"
	$Char_bank[16][8]     = "x x xx"
	$Char_bank[16][9]     = " xxxx "
	$Char_bank[16][10]    = "  x   "
	$Char_bank[16][11]    = "  x   "

	; Character 1
	$Char_bank_chr[17]    = "1"
	$Char_bank_width[17]  = "4"
	$Char_bank_height[17] = "8"
	$Char_bank[17][1]     = " xx "
	$Char_bank[17][2]     = "xxx "
	$Char_bank[17][3]     = " xx "
	$Char_bank[17][4]     = " xx "
	$Char_bank[17][5]     = " xx "
	$Char_bank[17][6]     = " xx "
	$Char_bank[17][7]     = " xx "
	$Char_bank[17][8]     = "xxxx"

	; Character ,
	$Char_bank_chr[18]    = ","
	$Char_bank_width[18]  = "2"
	$Char_bank_height[18] = "4"
	$Char_bank[18][1]     = "xx"
	$Char_bank[18][2]     = "xx"
	$Char_bank[18][3]     = "xx"
	$Char_bank[18][4]     = "x "

	; Character 0
	$Char_bank_chr[19]    = "0"
	$Char_bank_width[19]  = "6"
	$Char_bank_height[19] = "8"
	$Char_bank[19][1]     = " xxxx "
	$Char_bank[19][2]     = "xx  xx"
	$Char_bank[19][3]     = "xx  xx"
	$Char_bank[19][4]     = "xx  xx"
	$Char_bank[19][5]     = "xx  xx"
	$Char_bank[19][6]     = "xx  xx"
	$Char_bank[19][7]     = "xx  xx"
	$Char_bank[19][8]     = " xxxx "

	; Character B
	$Char_bank_chr[20]    = "B"
	$Char_bank_width[20]  = "6"
	$Char_bank_height[20] = "8"
	$Char_bank[20][1]     = "xxxxx "
	$Char_bank[20][2]     = "xx  xx"
	$Char_bank[20][3]     = "xx  xx"
	$Char_bank[20][4]     = "xxxxx "
	$Char_bank[20][5]     = "xx  xx"
	$Char_bank[20][6]     = "xx  xx"
	$Char_bank[20][7]     = "xx  xx"
	$Char_bank[20][8]     = "xxxxx "

	; Character a
	$Char_bank_chr[21]    = "a"
	$Char_bank_width[21]  = "6"
	$Char_bank_height[21] = "6"
	$Char_bank[21][1]     = " xxxx "
	$Char_bank[21][2]     = "    xx"
	$Char_bank[21][3]     = " xxxxx"
	$Char_bank[21][4]     = "xx  xx"
	$Char_bank[21][5]     = "xx  xx"
	$Char_bank[21][6]     = " xxxxx"

	; Character t
	$Char_bank_chr[22]    = "t"
	$Char_bank_width[22]  = "4"
	$Char_bank_height[22] = "8"
	$Char_bank[22][1]     = "xx  "
	$Char_bank[22][2]     = "xx  "
	$Char_bank[22][3]     = "xxxx"
	$Char_bank[22][4]     = "xx  "
	$Char_bank[22][5]     = "xx  "
	$Char_bank[22][6]     = "xx  "
	$Char_bank[22][7]     = "xx  "
	$Char_bank[22][8]     = " xxx"

	; Character l
	$Char_bank_chr[23]    = "l"
	$Char_bank_width[23]  = "2"
	$Char_bank_height[23] = "9"
	$Char_bank[23][1]     = "xx"
	$Char_bank[23][2]     = "xx"
	$Char_bank[23][3]     = "xx"
	$Char_bank[23][4]     = "xx"
	$Char_bank[23][5]     = "xx"
	$Char_bank[23][6]     = "xx"
	$Char_bank[23][7]     = "xx"
	$Char_bank[23][8]     = "xx"
	$Char_bank[23][9]     = "xx"

	; Character e
	$Char_bank_chr[24]    = "e"
	$Char_bank_width[24]  = "6"
	$Char_bank_height[24] = "6"
	$Char_bank[24][1]     = " xxxx "
	$Char_bank[24][2]     = "xx  xx"
	$Char_bank[24][3]     = "xxxxxx"
	$Char_bank[24][4]     = "xx    "
	$Char_bank[24][5]     = "xx    "
	$Char_bank[24][6]     = " xxxxx"

	; Character f
	$Char_bank_chr[25]    = "f"
	$Char_bank_width[25]  = "4"
	$Char_bank_height[25] = "9"
	$Char_bank[25][1]     = " xxx"
	$Char_bank[25][2]     = "xx  "
	$Char_bank[25][3]     = "xx  "
	$Char_bank[25][4]     = "xxx "
	$Char_bank[25][5]     = "xx  "
	$Char_bank[25][6]     = "xx  "
	$Char_bank[25][7]     = "xx  "
	$Char_bank[25][8]     = "xx  "
	$Char_bank[25][9]     = "xx  "

	; Character r
	$Char_bank_chr[26]    = "r"
	$Char_bank_width[26]  = "4"
	$Char_bank_height[26] = "6"
	$Char_bank[26][1]     = "xx x"
	$Char_bank[26][2]     = "xxxx"
	$Char_bank[26][3]     = "xx  "
	$Char_bank[26][4]     = "xx  "
	$Char_bank[26][5]     = "xx  "
	$Char_bank[26][6]     = "xx  "

	; Character R
	$Char_bank_chr[27]    = "R"
	$Char_bank_width[27]  = "7"
	$Char_bank_height[27] = "8"
	$Char_bank[27][1]     = "xxxxx  "
	$Char_bank[27][2]     = "xx  xx "
	$Char_bank[27][3]     = "xx  xx "
	$Char_bank[27][4]     = "xx  xx "
	$Char_bank[27][5]     = "xxxxx  "
	$Char_bank[27][6]     = "xx xx  "
	$Char_bank[27][7]     = "xx  xx "
	$Char_bank[27][8]     = "xx   xx"

	; Character u
	$Char_bank_chr[28]    = "u"
	$Char_bank_width[28]  = "6"
	$Char_bank_height[28] = "6"
	$Char_bank[28][1]     = "xx  xx"
	$Char_bank[28][2]     = "xx  xx"
	$Char_bank[28][3]     = "xx  xx"
	$Char_bank[28][4]     = "xx  xx"
	$Char_bank[28][5]     = "xx  xx"
	$Char_bank[28][6]     = " xxxxx"

	; Character s
	$Char_bank_chr[29]    = "s"
	$Char_bank_width[29]  = "5"
	$Char_bank_height[29] = "6"
	$Char_bank[29][1]     = " xxxx"
	$Char_bank[29][2]     = "xx   "
	$Char_bank[29][3]     = "xxxx "
	$Char_bank[29][4]     = " xxxx"
	$Char_bank[29][5]     = "   xx"
	$Char_bank[29][6]     = "xxxx "

	; Character i
	$Char_bank_chr[30]    = "i"
	$Char_bank_width[30]  = "2"
	$Char_bank_height[30] = "8"
	$Char_bank[30][1]     = "xx"
	$Char_bank[30][2]     = "  "
	$Char_bank[30][3]     = "xx"
	$Char_bank[30][4]     = "xx"
	$Char_bank[30][5]     = "xx"
	$Char_bank[30][6]     = "xx"
	$Char_bank[30][7]     = "xx"
	$Char_bank[30][8]     = "xx"

	; Character F
	$Char_bank_chr[31]    = "F"
	$Char_bank_width[31]  = "5"
	$Char_bank_height[31] = "8"
	$Char_bank[31][1]     = "xxxxx"
	$Char_bank[31][2]     = "xx   "
	$Char_bank[31][3]     = "xx   "
	$Char_bank[31][4]     = "xxxxx"
	$Char_bank[31][5]     = "xx   "
	$Char_bank[31][6]     = "xx   "
	$Char_bank[31][7]     = "xx   "
	$Char_bank[31][8]     = "xx   "

	; Character .
	$Char_bank_chr[32]    = "."
	$Char_bank_width[32]  = "2"
	$Char_bank_height[32] = "2"
	$Char_bank[32][1]     = "xx"
	$Char_bank[32][2]     = "xx"

	; Character A
	$Char_bank_chr[33]    = "A"
	$Char_bank_width[33]  = "7"
	$Char_bank_height[33] = "8"
	$Char_bank[33][1]     = "  xxx  "
	$Char_bank[33][2]     = "  xxx  "
	$Char_bank[33][3]     = " xx xx "
	$Char_bank[33][4]     = " xx xx "
	$Char_bank[33][5]     = " xx xx "
	$Char_bank[33][6]     = "xxxxxxx"
	$Char_bank[33][7]     = "xx   xx"
	$Char_bank[33][8]     = "xx   xx"

	; Character p
	$Char_bank_chr[34]    = "p"
	$Char_bank_width[34]  = "6"
	$Char_bank_height[34] = "8"
	$Char_bank[34][1]     = "xxxxx "
	$Char_bank[34][2]     = "xx  xx"
	$Char_bank[34][3]     = "xx  xx"
	$Char_bank[34][4]     = "xx  xx"
	$Char_bank[34][5]     = "xx  xx"
	$Char_bank[34][6]     = "xxxxx "
	$Char_bank[34][7]     = "xx    "
	$Char_bank[34][8]     = "xx    "

	; Character :
	$Char_bank_chr[35]    = ":"
	$Char_bank_width[35]  = "2"
	$Char_bank_height[35] = "6"
	$Char_bank[35][1]     = "xx"
	$Char_bank[35][2]     = "xx"
	$Char_bank[35][3]     = "  "
	$Char_bank[35][4]     = "  "
	$Char_bank[35][5]     = "xx"
	$Char_bank[35][6]     = "xx"

	; Character N
	$Char_bank_chr[36]    = "N"
	$Char_bank_width[36]  = "6"
	$Char_bank_height[36] = "8"
	$Char_bank[36][1]     = "xx   x"
	$Char_bank[36][2]     = "xxx  x"
	$Char_bank[36][3]     = "xxxx x"
	$Char_bank[36][4]     = "x xxxx"
	$Char_bank[36][5]     = "x  xxx"
	$Char_bank[36][6]     = "x   xx"
	$Char_bank[36][7]     = "x    x"
	$Char_bank[36][8]     = "x    x"

	; Character L
	$Char_bank_chr[37]    = "L"
	$Char_bank_width[37]  = "5"
	$Char_bank_height[37] = "8"
	$Char_bank[37][1]     = "xx   "
	$Char_bank[37][2]     = "xx   "
	$Char_bank[37][3]     = "xx   "
	$Char_bank[37][4]     = "xx   "
	$Char_bank[37][5]     = "xx   "
	$Char_bank[37][6]     = "xx   "
	$Char_bank[37][7]     = "xx   "
	$Char_bank[37][8]     = "xxxxx"

	; Character H
	$Char_bank_chr[38]    = "H"
	$Char_bank_width[38]  = "7"
	$Char_bank_height[38] = "8"
	$Char_bank[38][1]     = "xx   xx"
	$Char_bank[38][2]     = "xx   xx"
	$Char_bank[38][3]     = "xx   xx"
	$Char_bank[38][4]     = "xxxxxxx"
	$Char_bank[38][5]     = "xx   xx"
	$Char_bank[38][6]     = "xx   xx"
	$Char_bank[38][7]     = "xx   xx"
	$Char_bank[38][8]     = "xx   xx"

	; Character n
	$Char_bank_chr[39]    = "n"
	$Char_bank_width[39]  = "6"
	$Char_bank_height[39] = "6"
	$Char_bank[39][1]     = "xxxxx "
	$Char_bank[39][2]     = "xx  xx"
	$Char_bank[39][3]     = "xx  xx"
	$Char_bank[39][4]     = "xx  xx"
	$Char_bank[39][5]     = "xx  xx"
	$Char_bank[39][6]     = "xx  xx"

	; Character o
	$Char_bank_chr[40]    = "o"
	$Char_bank_width[40]  = "6"
	$Char_bank_height[40] = "6"
	$Char_bank[40][1]     = " xxxx "
	$Char_bank[40][2]     = "xx  xx"
	$Char_bank[40][3]     = "xx  xx"
	$Char_bank[40][4]     = "xx  xx"
	$Char_bank[40][5]     = "xx  xx"
	$Char_bank[40][6]     = " xxxx "

	; Character c
	$Char_bank_chr[41]    = "c"
	$Char_bank_width[41]  = "5"
	$Char_bank_height[41] = "6"
	$Char_bank[41][1]     = " xxxx"
	$Char_bank[41][2]     = "xx   "
	$Char_bank[41][3]     = "xx   "
	$Char_bank[41][4]     = "xx   "
	$Char_bank[41][5]     = "xx   "
	$Char_bank[41][6]     = " xxxx"

	; Character d
	$Char_bank_chr[42]    = "d"
	$Char_bank_width[42]  = "6"
	$Char_bank_height[42] = "9"
	$Char_bank[42][1]     = "    xx"
	$Char_bank[42][2]     = "    xx"
	$Char_bank[42][3]     = "    xx"
	$Char_bank[42][4]     = " xxxxx"
	$Char_bank[42][5]     = "xx  xx"
	$Char_bank[42][6]     = "xx  xx"
	$Char_bank[42][7]     = "xx  xx"
	$Char_bank[42][8]     = "xx  xx"
	$Char_bank[42][9]     = " xxxxx"

	; Character U
	$Char_bank_chr[43]    = "U"
	$Char_bank_width[43]  = "7"
	$Char_bank_height[43] = "8"
	$Char_bank[43][1]     = "xx   xx"
	$Char_bank[43][2]     = "xx   xx"
	$Char_bank[43][3]     = "xx   xx"
	$Char_bank[43][4]     = "xx   xx"
	$Char_bank[43][5]     = "xx   xx"
	$Char_bank[43][6]     = "xx   xx"
	$Char_bank[43][7]     = "xx   xx"
	$Char_bank[43][8]     = " xxxxx "

	; Character k
	$Char_bank_chr[44]    = "k"
	$Char_bank_width[44]  = "6"
	$Char_bank_height[44] = "9"
	$Char_bank[44][1]     = "xx    "
	$Char_bank[44][2]     = "xx    "
	$Char_bank[44][3]     = "xx    "
	$Char_bank[44][4]     = "xx  xx"
	$Char_bank[44][5]     = "xx xx "
	$Char_bank[44][6]     = "xxxx  "
	$Char_bank[44][7]     = "xxxx  "
	$Char_bank[44][8]     = "xx xx "
	$Char_bank[44][9]     = "xx  xx"

	; Character 4
	$Char_bank_chr[45]    = "4"
	$Char_bank_width[45]  = "6"
	$Char_bank_height[45] = "8"
	$Char_bank[45][1]     = "    x "
	$Char_bank[45][2]     = "   xx "
	$Char_bank[45][3]     = "  xxx "
	$Char_bank[45][4]     = " x xx "
	$Char_bank[45][5]     = "x  xx "
	$Char_bank[45][6]     = "xxxxxx"
	$Char_bank[45][7]     = "   xx "
	$Char_bank[45][8]     = "   xx "

	; Character G
	$Char_bank_chr[46]    = "G"
	$Char_bank_width[46]  = "7"
	$Char_bank_height[46] = "8"
	$Char_bank[46][1]     = " xxxxxx"
	$Char_bank[46][2]     = "xx     "
	$Char_bank[46][3]     = "xx     "
	$Char_bank[46][4]     = "xx     "
	$Char_bank[46][5]     = "xx  xxx"
	$Char_bank[46][6]     = "xx   xx"
	$Char_bank[46][7]     = "xx   xx"
	$Char_bank[46][8]     = " xxxxxx"

	; Character y
	$Char_bank_chr[47]    = "y"
	$Char_bank_width[47]  = "6"
	$Char_bank_height[47] = "8"
	$Char_bank[47][1]     = "xx  xx"
	$Char_bank[47][2]     = "xx  xx"
	$Char_bank[47][3]     = " xxxx "
	$Char_bank[47][4]     = " xxxx "
	$Char_bank[47][5]     = "  xx  "
	$Char_bank[47][6]     = "  xx  "
	$Char_bank[47][7]     = " xx   "
	$Char_bank[47][8]     = " xx   "

	; Character (
	$Char_bank_chr[48]    = "("
	$Char_bank_width[48]  = "4"
	$Char_bank_height[48] = "11"
	$Char_bank[48][1]     = "  xx"
	$Char_bank[48][2]     = " xx "
	$Char_bank[48][3]     = " xx "
	$Char_bank[48][4]     = "xx  "
	$Char_bank[48][5]     = "xx  "
	$Char_bank[48][6]     = "xx  "
	$Char_bank[48][7]     = "xx  "
	$Char_bank[48][8]     = "xx  "
	$Char_bank[48][9]     = " xx "
	$Char_bank[48][10]    = " xx "
	$Char_bank[48][11]    = "  xx"

	; Character 7
	$Char_bank_chr[49]    = "7"
	$Char_bank_width[49]  = "6"
	$Char_bank_height[49] = "8"
	$Char_bank[49][1]     = "xxxxxx"
	$Char_bank[49][2]     = "    xx"
	$Char_bank[49][3]     = "   xx "
	$Char_bank[49][4]     = "   xx "
	$Char_bank[49][5]     = "   xx "
	$Char_bank[49][6]     = "  xx  "
	$Char_bank[49][7]     = "  xx  "
	$Char_bank[49][8]     = "  xx  "

	; Character P
	$Char_bank_chr[50]    = "P"
	$Char_bank_width[50]  = "6"
	$Char_bank_height[50] = "8"
	$Char_bank[50][1]     = "xxxxx "
	$Char_bank[50][2]     = "xx  xx"
	$Char_bank[50][3]     = "xx  xx"
	$Char_bank[50][4]     = "xx  xx"
	$Char_bank[50][5]     = "xxxxx "
	$Char_bank[50][6]     = "xx    "
	$Char_bank[50][7]     = "xx    "
	$Char_bank[50][8]     = "xx    "

	; Character m
	$Char_bank_chr[51]    = "m"
	$Char_bank_width[51]  = "10"
	$Char_bank_height[51] = "6"
	$Char_bank[51][1]     = "xxxxx xxx "
	$Char_bank[51][2]     = "xx  xx  xx"
	$Char_bank[51][3]     = "xx  xx  xx"
	$Char_bank[51][4]     = "xx  xx  xx"
	$Char_bank[51][5]     = "xx  xx  xx"
	$Char_bank[51][6]     = "xx  xx  xx"

	Return "success" 	

EndFunc
